const STRINGS = {
  en: {
    welcome: "Welcome, ninja! Ready to multiply?",
    start: "Play Game",
    learningMode: "Learning Mode",
    quizMode: "Quiz Mode",
    shop: "Shop",
    settings: "Settings",
    selectLevel: "Choose multiplication table",
    learnTitle: n => `Table of ${n}`,
    quizTitle: n => `Quiz: table of ${n}`,
    learnPrompt: n => `Table of ${n} – Learn first or take the quiz?`,
    correct: (a,b,p) => `Great! ${a} × ${b} = ${p}`,
    wrong: "Oops! Try again",
    levelComplete: n => `Level ${n} complete! New skin unlocked!`,
    back: "Back",
    shopTitle: "Shop",
    settingsTitle: "Settings",
    settingsInfo: "No extra settings yet",
    coins: c => `Coins: ${c}`,
    languageLabel: "Language: EN",
    redNinja: "Red Ninja",
    blueNinja: "Blue Ninja",
    notEnough: "Not enough coins",
    purchased: name => `${name} purchased`,
    equipped: name => `${name} equipped`
  },
  es: {
    welcome: "¡Bienvenido, ninja! ¿Listo para multiplicar?",
    start: "Jugar",
    learningMode: "Modo Aprender",
    quizMode: "Modo Quiz",
    shop: "Tienda",
    settings: "Configuración",
    selectLevel: "Elige tabla de multiplicar",
    learnTitle: n => `Tabla del ${n}`,
    quizTitle: n => `Quiz: tabla del ${n}`,
    learnPrompt: n => `Tabla del ${n} – ¿Aprender primero o hacer el quiz?`,
    correct: (a,b,p) => `¡Excelente! ${a} × ${b} = ${p}`,
    wrong: "¡Ups! Intenta de nuevo",
    levelComplete: n => `¡Nivel ${n} completado! ¡Nueva skin desbloqueada!`,
    back: "Volver",
    shopTitle: "Tienda",
    settingsTitle: "Configuración",
    settingsInfo: "Sin ajustes extra",
    coins: c => `Monedas: ${c}`,
    languageLabel: "Idioma: ES",
    redNinja: "Ninja Rojo",
    blueNinja: "Ninja Azul",
    notEnough: "No hay suficientes monedas",
    purchased: name => `${name} comprado`,
    equipped: name => `${name} equipado`
  }
};
